export enum OrderType {
    TAKE_AWAY = "TAKE_AWAY",
    DINE_IN = "DINE_IN",
}

export enum OrderStatus {
    ORDER_PLACED = "ORDER_PLACED",
    ORDER_REJECTED = "ORDER_REJECTED",
    ORDER_ACCEPTED = "ORDER_ACCEPTED",
    ORDER_CANCELED = "ORDER_CANCELED",
}
